version: "3.9"
services:
  db:
    image: postgres:15
    container_name: investment-matchmaker-postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: investment-matchmaker-mailhog
    ports: ["1025:1025", "8025:8025"]
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
